buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24'
  }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.notificationtracker'
version = '0.1.0'

android {
  namespace 'expo.modules.notificationtracker'
  compileSdkVersion rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
